## Import Neccessary Libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing
import nltk
import re

## EDA

In [2]:
data_amazon = pd.read_csv('../Amazon Prime Recommendation/amazon_prime_titles.csv')

In [3]:
data_amazon

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

In [4]:
data_amazon.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [5]:
data_amazon.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

In [6]:
data_amazon.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [7]:
data_amazon['title'].head()

0     The Grand Seduction
1    Take Care Good Night
2    Secrets of Deception
3      Pink: Staying True
4           Monster Maker
Name: title, dtype: object

In [8]:
data_amazon['director'].head()

0      Don McKellar
1      Girish Joshi
2       Josh Webber
3    Sonia Anderson
4      Giles Foster
Name: director, dtype: object

In [9]:
data_amazon.isnull().sum()

show_id            0
type               0
title              0
director        2083
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [10]:
data_amazon.describe(include='all')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,9668,9668,9668,7585,8435,672,155,9668.000000,9331,9668,9668,9668
unique,9668,2,9668,5773,7927,86,84,NaN,24,219,518,9414
top,s1,Movie,The Grand Seduction,Mark Knight,Maggie Binkley,United States,"March 30, 2021",NaN,13+,1 Season,Drama,"Arpo was designed as a commando robot, built a..."
freq,1,7814,1,113,56,253,14,NaN,2117,1342,986,15
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.341849,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.922482,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1920.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

## Data Cleansing

In [11]:
df = data_amazon[['title', 'director', 'cast', 'listed_in', 'description']]

df['description_1'] = df['title'] + ': ' + df['description']
df.dropna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          9668 non-null   object
 1   director       7585 non-null   object
 2   cast           8435 non-null   object
 3   listed_in      9668 non-null   object
 4   description    9668 non-null   object
 5   description_1  9668 non-null   object
dtypes: object(6)
memory usage: 453.3+ KB

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24608\2206755615.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description_1'] = df['title'] + ': ' + df['description']

In [12]:
df.head()

,title,director,cast,listed_in,description,description_1
0,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent","Comedy, Drama",A small fishing village must procure a local d...,The Grand Seduction: A small fishing village m...
1,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar","Drama, International",A Metro Family decides to fight a Cyber Crimin...,Take Care Good Night: A Metro Family decides t...
2,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...","Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Secrets of Deception: After a man discovers hi...
3,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",Documentary,"Pink breaks the mold once again, bringing her ...",Pink: Staying True: Pink breaks the mold once ...
4,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...","Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Monster Maker: Teenage Matt Banting wants to w...

In [13]:
df.isnull().sum()

title               0
director         2083
cast             1233
listed_in           0
description         0
description_1       0
dtype: int64

## Build a Recommendation System

In [14]:
nltk.download('stopwords')

stop_words = nltk.corpus.stopwords.words('english')

def normalize_document(doc):
    # lower case and remove special characters\whitespaces
    doc = re.sub(r'[^a-zA-Z0-9\s]', '', doc, re.I|re.A)
    doc = doc.lower()
    doc = doc.strip()
    # tokenize document
    tokens = nltk.word_tokenize(doc)
    # filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc
normalize_corpus = np.vectorize(normalize_document)

norm_corpus = normalize_corpus(list(df['description_1']))
len(norm_corpus)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

9668

#### Extract TF-IDF Features

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(ngram_range=(1, 2), min_df=2)
tfidf_matrix = tf.fit_transform(norm_corpus)
tfidf_matrix.shape

(9668, 35435)

#### Compute Pairwise Document Similarity

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

doc_sim = cosine_similarity(tfidf_matrix)
doc_sim_df = pd.DataFrame(doc_sim)
doc_sim_df.head()

,0,1,2,3,4,5,6,7,8,9,...,9658,9659,9660,9661,9662,9663,9664,9665,9666,9667
0,1.000000,0.0,0.000000,0.027287,0.000000,0.000000,0.005701,0.007987,0.0,0.0,...,0.010952,0.000000,0.000000,0.0,0.000000,0.013510,0.0,0.0,0.0,0.000000
1,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.076408,0.0,0.0,0.0,0.000000
2,0.000000,0.0,1.000000,0.000000,0.012213,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.026954,0.0,0.040115,0.043708,0.0,0.0,0.0,0.000000
3,0.027287,0.0,0.000000,1.000000,0.000000,0.005293,0.000000,0.018554,0.0,0.0,...,0.000000,0.022347,0.000000,0.0,0.000000,0.022091,0.0,0.0,0.0,0.004127
4,0.000000,0.0,0.012213,0.000000,1.000000,0.013718,0.010808,0.000000,0.0,0.0,...,0.000000,0.000000,0.019283,0.0,0.000000,0.000000,0.0,0.0,0.0,0.017393

#### Get List of Movies Titles

In [17]:
movies_list = df['title'].values
movies_list

array(['The Grand Seduction', 'Take Care Good Night',
       'Secrets of Deception', ..., 'Outpost', 'Maradona: Blessed Dream',
       'Harry Brown'], dtype=object)

In [18]:
movies_list.shape

(9668,)

#### Find Top Similar Movies for a Sample Movie

In [19]:
# Find movie ID
movie_id = np.where(movies_list == 'The Grand Seduction')[0][0]
movie_id

0

#### Get Similiar Movies

In [20]:
movie_similarities = doc_sim_df.iloc[movie_id].values
movie_similarities

array([1., 0., 0., ..., 0., 0., 0.])

#### Get top 5 similar movie IDs

In [21]:
similar_movie_id = np.argsort(-movie_similarities)[1:6]
similar_movie_id

array([ 455, 9098, 7312, 4464, 2638], dtype=int64)

In [22]:
similar_movies = movies_list[similar_movie_id]
similar_movies

array(['The Secret of Roan Inish', 'Squirm', 'Frankenfish',
       'Kitty Mammas', "Doctor Blood's Coffin"], dtype=object)

## Build a Movie Recommender Function to Recommend Top 5 Similar Movies For Any Movie

#### The movie title, movie title list and document similarity matrix dataframe will be given as inputs to the function

In [23]:
def movie_recommender(movie_title, movies=movies_list, doc_sims=doc_sim_df):
    # find movie id
    movie_idx = np.where(movies == movie_title)[0][0]
    # get movie similarities
    movie_similarities = doc_sims.iloc[movie_idx].values
    # get top 5 similar movie IDs
    similar_movie_idxs = np.argsort(-movie_similarities)[1:6]
    # get top 5 movies
    similar_movies = movies[similar_movie_idxs]
    # return the top 5 movies
    return similar_movies

In [24]:
df.columns

Index(['title', 'director', 'cast', 'listed_in', 'description',
       'description_1'],
      dtype='object')

In [25]:
pop_movies = df.sort_values(by='director', ascending=False)
pop_movies.head()

,title,director,cast,listed_in,description,description_1
4072,"Eriko, Pretended",藤村明世,"久保陽香, 岡田篤哉, 似鳥美貴, 辰寿広美, 真弓, 齋藤雅弘, 時光陸, 土佐和成, 小...","Arthouse, Comedy, Drama",Eriko returns home to attend her sister's fune...,"Eriko, Pretended: Eriko returns home to attend..."
7499,Black's Game,Óskar Thór Axelsson,"Vignir Rafnlborsson Val, Thor Kristjansson, Jo...",Suspense,"To pay down a debt, a student joins a small un...","Black's Game: To pay down a debt, a student jo..."
3698,Agathe Cléry,Étienne Chatiliez,"Valérie Lemercier, Anthony Kavanagh, Dominique...",Comedy,Agathe Cléry is a hard working and modern mark...,Agathe Cléry: Agathe Cléry is a hard working a...
1754,Mambo Italiano,Émile Gaudreault,"Luke Kirby, Claudia Ferri, Peter Miller, Paul ...","Comedy, Drama, LGBTQ",Angelo Barberini is the oddball son of Italian...,Mambo Italiano: Angelo Barberini is the oddbal...
4594,Compulsion,Ángel González,"Marina Esteve, Paco Manzanedo, Susana Abaitua,...","Drama, Horror, Suspense",A fairytale relationship comes to an end when ...,Compulsion: A fairytale relationship comes to ...

In [26]:
df.title.values[:50]

array(['The Grand Seduction', 'Take Care Good Night',
       'Secrets of Deception', 'Pink: Staying True', 'Monster Maker',
       'Living With Dinosaurs', 'Hired Gun', 'Grease Live!',
       'Global Meltdown', "David's Mother", 'Forest Fairies', 'Take Care',
       'The Night Eats The World', 'Resilencia',
       'Elon Musk: The Real Life Iron Man', "Summer '03", 'Zoombies',
       'Zoo Babies', 'Zoë Coombs Marr: Bossy Bottom', 'Zoe', 'Zoboomafoo',
       'Zo Zo Zombie: Mini-Series', 'Zis Boom Bah', 'ZeroZeroZero',
       'Zandalee', 'Zambezi: Force of Life', 'Zahara: The Return',
       'Z: The Beginning of Everything', 'Yu-Gi-Oh! Zexal',
       'Yu-Gi-Oh! ARC-V', "Yu-Gi-Oh! 5D's", 'Your Bleeped Up Brain',
       'Young Lovers', 'Young Love (at the Sun Factory)',
       'Young Love (at Bowery Ballroom)', 'Young Lions', "You're Not You",
       'You, Me and Him', 'Yoga with Sound Meditations',
       'Yoga to Harness Your Chakra Energy',
       'Yoga to Ease Flight Anxiety', 'Yoga to Break Any Habit',
       'Yoga Therapy For Back Pain, Neck Pain & Stress Relief - Lindsey Samper',
       'Yoga Savasana Relaxation', 'Yoga for Relaxation Anywhere',
       'Yoga for Relaxation and Stress Relief Anywhere',
       'Yoga for Relaxation and Stress Relief',
       'Yoga for Mindfulness and Meditation', "Yoga for Men's Health",
       'Yoga for Breath Awareness'], dtype=object)

In [27]:
col=df.title.values[:50]

#### Get Popular Movie Recommendations

In [28]:
for movie in col:
    print('Movie:', movie)
    print('Top 5 recommended Movies:', movie_recommender(movie_title=movie))
    print()

Movie: The Grand Seduction
Top 5 recommended Movies: ['The Secret of Roan Inish' 'Squirm' 'Frankenfish' 'Kitty Mammas'
 "Doctor Blood's Coffin"]

Movie: Take Care Good Night
Top 5 recommended Movies: ['Love and Marriage' 'Billy the Exterminator' 'The Zookeeper'
 'The Good Night' 'Transfert']

Movie: Secrets of Deception
Top 5 recommended Movies: ['Blackmail' '41' 'Mad Dogs' 'White Dragon' 'Omerta: The Act Of Silence']

Movie: Pink: Staying True
Top 5 recommended Movies: ['Pink - Love of Girls' 'Pink Heat'
 "Murder City Devils - Rock & Roll Won't Wait"
 'Pink Floyd: The Dark Side of the Moon'
 'Sons of the Soil : Jaipur Pink Panthers']

Movie: Monster Maker
Top 5 recommended Movies: ['Grinders' 'Some Freaks' 'The Night is Young'
 'Matt Braunger: Finally Live In Portland' 'Matt Besser: Pot Humor']

Movie: Living With Dinosaurs
Top 5 recommended Movies: ['Season for Love Songs' 'Child Support' 'Oddball' 'West of Nevada'
 'Love and Love Only']

Movie: Hired Gun
Top 5 recommended Movies: ['Phungus & Mowld' 'Padi Padi Leche Manasu' 'I Always Said After'
 'Winner Take All' 'The Raveonettes']

Movie: Grease Live!
Top 5 recommended Movies: ['Social Animals' 'For Better for Worse' "Porky's" 'To Let' 'Videola']

Movie: Global Meltdown
Top 5 recommended Movies: ['Into the Waves' 'Blue Thunder'
 'What Went Wrong: Countdown to Catastrophe' 'Liberty City The Movie'
 'No Exit']

Movie: David's Mother
Top 5 recommended Movies: ['Scarlet' 'Not Wanted' 'Cider with Rosie' 'A Different Loyalty'
 'Blood and Lace']

Movie: Forest Fairies
Top 5 recommended Movies: ['Netru Indru' 'Fairytale: A True Story' 'Attraction to Paris' 'Mirugaa'
 'Song of the Cloud Forest']

Movie: Take Care
Top 5 recommended Movies: ['Raising Victor Vargas' 'One More Flip' 'All The Men In My Life'
 'Jack Goes Home' 'The Ex (2006)']

Movie: The Night Eats The World
Top 5 recommended Movies: ['Bright Hill Road' 'Sister Mary Explains it All' 'Stag Hunt' 'Charlene'
 'Hostile']

Movie: Resilencia
Top 5 recommended Movies: ['Caillou' 'All Or Nothing: Toronto Maple Leafs' 'Ratter' 'Nootrenbadhu'
 'Vocabulary and Numbers with Harry the Bunny and Friends']

Movie: Elon Musk: The Real Life Iron Man
Top 5 recommended Movies: ['Elon Gold: Chosen & Taken' 'Blondie Maxwell Never Loses'
 'Yu-Gi-Oh! VRAINS' 'Frances' 'Sprinter']

Movie: Summer '03
Top 5 recommended Movies: ["Everybody's Talking About Jamie" 'Jamie Kennedy: Uncomfortable'
 "Mama's Song" 'The Tribe' 'Jamie: Drag Queen at 16']

Movie: Zoombies
Top 5 recommended Movies: ['Triassic Hunt' 'Number Zoo Adventures with Toddler Fun Learning'
 'Blippi Explores a Water Park!' 'Prince of Central Park' 'Paradise Park']

Movie: Zoo Babies
Top 5 recommended Movies: ['We Bought A Zoo' 'Number Zoo Adventures with Toddler Fun Learning'
 'Canticos' "Tom Hamilton's American Babies" 'Animalympics']

Movie: Zoë Coombs Marr: Bossy Bottom
Top 5 recommended Movies: ['Zo Zo Zombie: Mini-Series' 'Saving Zoë' '2ELEVEN' 'Sketchy Behaviour'
 'The Grand']

Movie: Zoe
Top 5 recommended Movies: ['My Zoe' 'Hidden Truth' 'Man From Texas (1948)' 'Best Night Ever'
 'What If']

Movie: Zoboomafoo
Top 5 recommended Movies: ['Wild Kratts' "Kratts' Creatures" 'The Judge' 'The Prankster'
 'In Remembrance of Martin']

Movie: Zo Zo Zombie: Mini-Series
Top 5 recommended Movies: ['Zoë Coombs Marr: Bossy Bottom' 'Saving Zoë' '2ELEVEN' 'Zombie Massacre'
 'Zomblies']

Movie: Zis Boom Bah
Top 5 recommended Movies: ['The Carducci Talent Show' 'Mister Maker' 'The Irish Comedy Tour'
 'Cheer Up' 'Big Top Pee-Wee']

Movie: ZeroZeroZero
Top 5 recommended Movies: ['Atlantic: A Year in the Wild' 'Gangsta' 'Space Dogs Tropical Adventure'
 'Timber Queen' 'Gajaar: Journey of the Soul']

Movie: Zandalee
Top 5 recommended Movies: ['Scorned' 'Scarlet' 'Creative Control' 'Romance Analyst'
 'The Perfect Husband']

Movie: Zambezi: Force of Life
Top 5 recommended Movies: ['River' 'Joanna Lumley: Jewel in the Nile' 'Mara: River of Death'
 '30 Minutes of Serenity'
 'Explore The Wildlife Kingdom: Lions - Kings of Africa']

Movie: Zahara: The Return
Top 5 recommended Movies: ['White Savior: Racism In The American Church' 'A Deadly Legend' 'Dhadak'
 'The Princess and The Marine' 'Black, White & Us']

Movie: Z: The Beginning of Everything
Top 5 recommended Movies: ['Exorcist: The Beginning' 'Prisoner Number A26188: Surviving Auschwitz'
 'Girl/Girl Scene' 'Liz: The Elizabeth Taylor Story'
 'Nature: Touching the Wild: Living with the Mule Deer of Deadman Gulch']

Movie: Yu-Gi-Oh! Zexal
Top 5 recommended Movies: ['Yu-Gi-Oh! ARC-V' 'Yu-Gi-Oh! VRAINS' 'Hellarious' "Yu-Gi-Oh! 5D's"
 'Making Sense']

Movie: Yu-Gi-Oh! ARC-V
Top 5 recommended Movies: ['Yu-Gi-Oh! VRAINS' 'Glee' 'Yu-Gi-Oh! Zexal'
 'Cobra Puma Golf All-Access Show' "Yu-Gi-Oh! 5D's"]

Movie: Yu-Gi-Oh! 5D's
Top 5 recommended Movies: ['Rev & Roll' 'Yu-Gi-Oh! ARC-V' 'Yu-Gi-Oh! Zexal' 'Yu-Gi-Oh! VRAINS'
 'The Perfect Sleep']

Movie: Your Bleeped Up Brain
Top 5 recommended Movies: ['BuzzFeed Unsolved: True Crime' 'Moonwalkers'
 'The Manchurian Candidate (2004)' 'Beyond the Sky' 'Being Taken']

Movie: Young Lovers
Top 5 recommended Movies: ['Pandora' 'The Carol Burnett Show' 'Elzaz' 'The First Silent Night'
 'Love is Blind']

Movie: Young Love (at the Sun Factory)
Top 5 recommended Movies: ['Young Love (at Bowery Ballroom)'
 'Learning with The GiggleBots: GiggleBellies' 'Sivappu Malli'
 'House of Hummingbird' 'Soñadora: A Rising Voices Film']

Movie: Young Love (at Bowery Ballroom)
Top 5 recommended Movies: ['Young Love (at the Sun Factory)' 'Electric Six'
 'Sleepytime Gorilla Museum' 'House of Hummingbird' 'Silver Stallion']

Movie: Young Lions
Top 5 recommended Movies: ['Strange Wilderness' 'Meendum Oru Mariyathai'
 'The Dancing Detective Dekadance' 'Inheritance' 'The Hunted']

Movie: You're Not You
Top 5 recommended Movies: ['Disconnect' 'Out in the Dark (English Subtitled)' 'Gleason'
 'Manadhai Thirudivittai' 'Palace']

Movie: You, Me and Him
Top 5 recommended Movies: ['Kung Fu Punch of Death' 'Mad to be Normal' 'The Best of I Love Lucy'
 'Guess How Much I Love You' 'The Lucy Show - Vol. 1']

Movie: Yoga with Sound Meditations
Top 5 recommended Movies: ['Yoga for Mindfulness and Meditation' 'Yoga For Beginners'
 '3 Simple Meditation Practices' "Yoga for Men's Health" 'Yes & Yoga']

Movie: Yoga to Harness Your Chakra Energy
Top 5 recommended Movies: ['16 Minute Chakra Garden Meditation' 'Yoga for Breath Awareness'
 'Soothing Waterfalls with Music' '30 Minutes of Water'
 '8 Minute Meditation to Forget and Forgive']

Movie: Yoga to Ease Flight Anxiety
Top 5 recommended Movies: ['Seated Yoga Level I 13 minutes' 'Yoga for Relaxation and Stress Relief'
 '9-Minute Yoga: Guided Meditation & Visualization'
 'Yoga for Relaxation and Stress Relief Anywhere'
 '6 Minutes of Yoga By The Ocean']

Movie: Yoga to Break Any Habit
Top 5 recommended Movies: ['Yoga For Restful Sleep with Dr. Daniel Nightingale'
 'Living Well With Dementia' 'Jacob Two-Two'
 '7 Minute Yoga Nidra for Focus' 'Yoga For Beginners']

Movie: Yoga Therapy For Back Pain, Neck Pain & Stress Relief - Lindsey Samper
Top 5 recommended Movies: ['15-Minute Yoga Flow 2.0 (Workout)' '15-Minute Yoga Core 1.0 Workout'
 '15-Minute Yoga Flow 1.0 (Workout)' '15-Minute Yoga Stretch 1.0 Workout'
 '15-Minute Yoga Power Flow 2.0 (Workout)']

Movie: Yoga Savasana Relaxation
Top 5 recommended Movies: ['Yoga for Relaxation Anywhere' 'Yoga for Relaxation and Stress Relief'
 '7 Minute Yoga Nidra for Focus'
 'Yoga for Relaxation and Stress Relief Anywhere'
 '6 Minutes of Yoga By The Ocean']

Movie: Yoga for Relaxation Anywhere
Top 5 recommended Movies: ['Yoga Savasana Relaxation' '7 Minute Yoga Nidra for Focus'
 'Yoga for Relaxation and Stress Relief'
 'Yoga for Relaxation and Stress Relief Anywhere'
 '6 Minutes of Yoga By The Ocean']

Movie: Yoga for Relaxation and Stress Relief Anywhere
Top 5 recommended Movies: ['Yoga for Relaxation and Stress Relief'
 '9-Minute Yoga: Guided Meditation & Visualization'
 'Yoga Savasana Relaxation' '6 Minutes of Yoga By The Ocean'
 'Living Well With Dementia']

Movie: Yoga for Relaxation and Stress Relief
Top 5 recommended Movies: ['Yoga for Relaxation and Stress Relief Anywhere'
 'Yoga Savasana Relaxation' 'Yoga for Abdominal Breathing'
 '6 Minutes of Yoga By The Ocean' 'Yoga for Relaxation Anywhere']

Movie: Yoga for Mindfulness and Meditation
Top 5 recommended Movies: ['Yoga with Sound Meditations' 'Yoga For Beginners'
 '3 Simple Meditation Practices' "Yoga for Men's Health"
 '15 Minute Ocean Meditation']

Movie: Yoga for Men's Health
Top 5 recommended Movies: ['Yoga for Mindfulness and Meditation' 'Yoga with Sound Meditations'
 'Yoga For Beginners' '3 Simple Meditation Practices'
 '7 Minute Yoga Nidra for Focus']

Movie: Yoga for Breath Awareness
Top 5 recommended Movies: ['Alternate Nostril Breathing' '6 Minutes of Yoga By The Ocean'
 '15-Minute Guided Meditation' '10-Minute Guided Meditation'
 'Yoga for Abdominal Breathing']